sudo: required
services:
  - docker

before_install:
  - sudo apt-add-repository multiverse 
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

install:
  - gem update --system
  - bundle install --path .bundle

script:
  - spec/support/specs.sh run

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
    # to figure out later
  - rvm: jruby-9.1.15.0
  - rvm: rbx-2
