sudo: required
services:
  - docker

before_install:
  - sudo apt-add-repository multiverse 
  - sudo apt-get update
  - sudo apt-get install -y sed
  - sudo apt-get install -y snmp
  - sudo apt-get install -y libsnmp-dev
  - sudo apt-get install -y snmpd
  - sudo apt-get install -y snmp-mibs-downloader 
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

before_script:
  - sudo download-mibs 
  - sudo sed -i 's/^mibs/#mibs/g' /etc/snmp/snmp.conf
  - spec/support/start_docker.sh
after_script: spec/support/stop_docker.sh

install:
  - bundle install --path .bundle

script:
  - bundle exec rake

language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
  - rvm:
    - ruby-head
