version: '3'
services:
  netsnmp:
    environment:
      - SNMP_HOST=snmp-server-emulator
      - SNMP_PORT=1161
      - CI=1
      - BUNDLE_SILENCE_ROOT_WARNING=1
      - BUNDLE_JOBS=10
    image: ruby:alpine
    depends_on:
      - snmp-server-emulator
    volumes:
      - ./:/home
    entrypoint:
      /home/spec/support/specs.sh

  snmp-server-emulator:
    image: honeyryderchuck/snmp-server-emulator:latest
    ports:
      - 1161:1161/udp
    volumes:
      - ./spec/support/snmpsim/:/home/snmp_server/.snmpsim
    command:
      - --v3-engine-id=000000000000000000000002
      - --agent-udpv4-endpoint=0.0.0.0:1161
      - --agent-udpv6-endpoint=[::0]:1161
      - --v3-user=simulator
      - --v3-auth-key=auctoritas
      - --v3-priv-key=privatus
      - --v3-user=authmd5
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=MD5
      - --v3-priv-proto=NONE
      - --v3-user=authsha
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=SHA
      - --v3-priv-proto=NONE
      - --v3-user=authprivshaaes
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=SHA
      - --v3-priv-key=maplesyrup
      - --v3-priv-proto=AES
      - --v3-user=authprivmd5aes
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=MD5
      - --v3-priv-key=maplesyrup
      - --v3-priv-proto=AES
      - --v3-user=authprivshades
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=SHA
      - --v3-priv-key=maplesyrup
      - --v3-priv-proto=DES
      - --v3-user=authprivmd5des
      - --v3-auth-key=maplesyrup
      - --v3-auth-proto=MD5
      - --v3-priv-key=maplesyrup
      - --v3-priv-proto=DES
      - --v3-user=unsafe
      - --v3-auth-proto=NONE
      - --v3-priv-proto=NONE
